
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "admin@admin.pl",
    "password": "admin123"
}

###

GET http://localhost:8000/financial-report-users
Authorization: Bearer 

###

GET http://localhost:8000/most-profitable-products
Authorization: Bearer 


###
GET http://localhost:8000/most-profitable-brands
Authorization: Bearer 


###
GET http://localhost:8000/profit-weekly
Authorization: Bearer 

###
GET http://localhost:8000/most-profitable-categories
Authorization: Bearer 

###
GET http://localhost:8000/orders-week
Authorization: Bearer 
###
GET http://localhost:8000/orders-month-periodic
Authorization: Bearer 

###
GET http://localhost:8000/orders-month
Authorization: Bearer 
###
GET http://localhost:8000/users-number
Authorization: Bearer 
###
GET http://localhost:8000/customers-around-world
Authorization: Bearer 
###


GET http://localhost:8000/traffic
Authorization: Bearer 

###
GET http://localhost:8000/dashboard
Authorization: Bearer 


###
//http://localhost:8000/user-comments/:userId
GET http://localhost:8000/user-comments/661ee379a881e0b8999aabee
Authorization: Bearer 

###
POST http://localhost:8000/update-discount
Authorization: Bearer 
Content-Type: application/json

{
    "productId": "661edcb6a881e0b8999aabcb", 
    "discountPercentage": 21
}