POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "admin@admin.pl",
    "password": "admin123"
}

###

GET http://localhost:8000/financial-report-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImFkZHJlc3MiOnsiY291bnRyeSI6IlBvbGFuZCIsInN0cmVldCI6IkJhcnRsYSIsInN1aXRlIjoiODBnIiwiY2l0eSI6IktyYWvDs3ciLCJ6aXBjb2RlIjoiMzAtMzg5In0sIl9pZCI6IjY2NjBjMDk1ZTYyMWUxNWE0NWMzNGQzOCIsImZpcnN0bmFtZSI6IlBpb3RyIiwibGFzdG5hbWUiOiLFmm1pYcWCZWsiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBhZG1pbi5wbCIsInBhc3N3b3JkIjoiJDJiJDEwJE41YXN1a2RHQkVqS2FNT0FzWDgyUE9EU0hmYmZwZ2l6Z281bVdTT1dvaml1V055Ny9xSXhTIiwicm9sZSI6ImFkbWluIiwicGhvbmUiOiI2NjYtNjY2LTY2NiIsIl9fdiI6MH0sImlhdCI6MTcxODQ2NjExOSwiZXhwIjoxNzE4NDY3MzE5fQ.SuGh3Qk5d8AFkbNyfoYItH7cpqsH2PoU9JoSMNSQxu0
