
POST http://localhost:8000/login
Content-Type: application/json

{
  "email": "Julianne.OConner@kory.org",
  "password": "haslo123"
}

###

GET http://localhost:8000/my-reviews
Authorization: Bearer 

###
GET http://localhost:8000/my-logs
Authorization: Bearer 


###
POST http://localhost:8000/register-user
Content-Type: application/json

{
    "firstname": "Christopher",
    "lastname": "Wilson",
    "username": "christopherwilson",
    "email": "christopher777@example.com",
    "password": "haslo123",
    "country": "Spain",
    "street": "Gran Via",
    "suite": "Apt 12",
    "city": "Madrid",
    "zipcode": "28013",
    "phone": "656-445-453"
}


###

POST http://localhost:8000/create-basket
Authorization: Bearer
Content-Type: application/json

{
    "products" : "661edcb6a881e0b8999aabcb",
    "currency" : "PLN",
    "payment_method" : "PayPal"
}

###

POST http://localhost:8000/my-shopping
Authorization: Bearer 
Content-Type: application/json

{
    "minTotalValue" : 1,
    "maxTotalValue" : 1000,
   "numberOfProducts": 3,
   "title" : "Huawei P30",
   "category" : "smartphones"
}

###
POST http://localhost:8000/add-review
Authorization: Bearer 
Content-Type: application/json

{
    "product_id" : "661edcb6a881e0b8999aabe4",
    "rating" : 2.1,
    "review" : "zmieniam zdanie 4 raz"
}


###
// http://localhost:8000/add-comment/:reviewId
POST http://localhost:8000/add-comment/666de26807f0a4c21dbf031d
Authorization: Bearer 
Content-Type: application/json

{
    "comment" : "Zgadzam sie z tobą ;)"
}



###
POST http://localhost:8000/search-products
Content-Type: application/json

{
    "title": "",
    "category": "lap",
    "minPrice": 0,
    "maxPrice": 10000,
    "minRating": 0,
    "maxRating": 5,
    "minDiscountPercentage": 0,
    "maxDiscountPercentage": 100,
    "minStock": 0,
    "maxStock": 100
}

###

POST http://localhost:8000/search-brands
Content-Type: application/json

{
    "name": "",
    "country": "fra",
    "city": "",
    "email": "",
    "phone": "",
    "website": "",
    "establishedYearMin": null,
    "establishedYearMax": null
}

###
//GET http://localhost:8000/products/:productId/all-reviews
GET http://localhost:8000/products/661edcb6a881e0b8999aabde/all-reviews

###
GET http://localhost:8000/all-products

###
GET http://localhost:8000/all-brands