
POST http://localhost:8000/login
Content-Type: application/json

{
  "email": "Julianne.OConner@kory.org",
  "password": "haslo123"
}

###

GET http://localhost:8000/my-reviews
Authorization: Bearer 

###
GET http://localhost:8000/my-logs
Authorization: Bearer 


###
POST http://localhost:8000/register-user
Content-Type: application/json

{
    "firstname": "Christopher",
    "lastname": "Wilson",
    "username": "christopherwilson",
    "email": "christopher777@example.com",
    "password": "haslo123",
    "country": "Spain",
    "street": "Gran Via",
    "suite": "Apt 12",
    "city": "Madrid",
    "zipcode": "28013",
    "phone": "656-445-453"
}


###
POST http://localhost:8000/add-review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImFkZHJlc3MiOnsiY291bnRyeSI6IlBvbGFuZCIsInN0cmVldCI6IkhvZWdlciBNYWxsIiwic3VpdGUiOiJBcHQuIDY5MiIsImNpdHkiOiJTb3V0aCBFbHZpcyIsInppcGNvZGUiOiI1MzkxOS00MjU3In0sIl9pZCI6IjY2MWVlMzc5YTg4MWUwYjg5OTlhYWJmMCIsImZpcnN0bmFtZSI6IlBhdHJpY2lhIiwibGFzdG5hbWUiOiJMZWJzYWNrIiwidXNlcm5hbWUiOiJLYXJpYW5uZSIsImVtYWlsIjoiSnVsaWFubmUuT0Nvbm5lckBrb3J5Lm9yZyIsInBhc3N3b3JkIjoiJDJiJDEwJEdONjRzSklrdHpxUnNtaENYT016WHUwUE1HZldSaktLSUVoMmJGWll3bjhKOHVzSlpSeFBPIiwicm9sZSI6ImN1c3RvbWVyIiwicGhvbmUiOiI0OTMtMTcwLTk2MjMgeDE1NiJ9LCJpYXQiOjE3MTg0ODIzNjYsImV4cCI6MTcxODQ4MzU2Nn0.KEaqGssFXvU0wIByEYyr2sFPjF_grLGJpKPg5YjND5Y
Content-Type: application/json

{
    "product_id" : "661edcb6a881e0b8999aabe4",
    "rating" : 2.1,
    "review" : "zmieniam zdanie 4 raz"
}


###
// http://localhost:8000/add-comment/:reviewId
POST http://localhost:8000/add-comment/666de26807f0a4c21dbf031d
Authorization: Bearer 
Content-Type: application/json

{
    "comment" : "Zgadzam sie z tobą ;)"
}

