# DO NOT FORGET Bearer

GET http://localhost:8000/tttest

GET http://localhost:8000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImFkZHJlc3MiOnsiY291bnRyeSI6IkF1c3RyaWEiLCJzdHJlZXQiOiJLYXR0aWUgVHVybnBpa2UiLCJzdWl0ZSI6IlN1aXRlIDE5OCIsImNpdHkiOiJMZWJzYWNrYnVyeSIsInppcGNvZGUiOiIzMTQyOC0yMjYxIn0sIl9pZCI6IjY2MWVlMzc5YTg4MWUwYjg5OTlhYWJmNiIsImZpcnN0bmFtZSI6IkNsZW1lbnRpbmEiLCJsYXN0bmFtZSI6IkR1QnVxdWUiLCJ1c2VybmFtZSI6Ik1vcmlhaC5TdGFudG9uIiwiZW1haWwiOiJSZXkuUGFkYmVyZ0BrYXJpbmEuYml6IiwicGFzc3dvcmQiOiIkMmIkMTAkN281Z1pDUEhkUG5SR3BtaFEzT0cwZTZvN2dzcU15M2EvS2ZJZm1lQXd5Ymg1VEU5RDBvQ3EiLCJwaG9uZSI6IjAyNC02NDgtMzgwNCJ9LCJpYXQiOjE3MTc2MDAyMTEsImV4cCI6MTcxNzYwMTQxMX0.00BHQHZF6oCcwc4bsHTypI1nG684kQcA_VSgi9SOVAk



